apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abzora-ingress
  namespace: abzora
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-body-size: "2m"
spec:
  ingressClassName: nginx
  rules:
    - host: api.abzora.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: abzora-api
                port:
                  number: 80
    - host: ws.abzora.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: abzora-websocket
                port:
                  number: 80
