apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: abianzo-api-pdb
  namespace: abianzo
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: abianzo-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: abianzo-worker-pdb
  namespace: abianzo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: abianzo-worker
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: abianzo-websocket-pdb
  namespace: abianzo
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: abianzo-websocket
