// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd81xKreHN5nyJiY-xbpMpruuXc9dV8uk',
    appId: '1:473004460649:web:688a272c89d6e8e902b0f8',
    messagingSenderId: '473004460649',
    projectId: 'abzora-bbed7',
    authDomain: 'abzora-bbed7.firebaseapp.com',
    storageBucket: 'abzora-bbed7.firebasestorage.app',
    measurementId: 'G-NYSLMQY368',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtutc5iB4sCamdxuMMk46cZoNkxYlc-jI',
    appId: '1:473004460649:android:d296d2172af8c78702b0f8',
    messagingSenderId: '473004460649',
    projectId: 'abzora-bbed7',
    storageBucket: 'abzora-bbed7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArhaszlsxljFagOd0qgi7mpCgrv9hbjlI',
    appId: '1:473004460649:ios:006db616363149f102b0f8',
    messagingSenderId: '473004460649',
    projectId: 'abzora-bbed7',
    storageBucket: 'abzora-bbed7.firebasestorage.app',
    iosBundleId: 'com.abdz.fashion.abzio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArhaszlsxljFagOd0qgi7mpCgrv9hbjlI',
    appId: '1:473004460649:ios:006db616363149f102b0f8',
    messagingSenderId: '473004460649',
    projectId: 'abzora-bbed7',
    storageBucket: 'abzora-bbed7.firebasestorage.app',
    iosBundleId: 'com.abdz.fashion.abzio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMXyII9XqX8lMvFrObqFoVPD9RMO29Qis',
    appId: '1:886864255867:web:22a05b45c157c8e272fbde',
    messagingSenderId: '886864255867',
    projectId: 'abzio-d99f9',
    authDomain: 'abzio-d99f9.firebaseapp.com',
    databaseURL: 'https://abzio-d99f9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'abzio-d99f9.firebasestorage.app',
    measurementId: 'G-VJM9K8C3Q9',
  );
}
