apiVersion: apps/v1
kind: Deployment
metadata:
  name: abianzo-api
  namespace: abianzo
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abianzo-worker
  namespace: abianzo
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abianzo-websocket
  namespace: abianzo
spec:
  replicas: 1
