apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abianzo-websocket-ingress
spec:
  tls:
    - hosts:
        - ws.staging.abianzo.example.com
      secretName: staging-abianzo-ws-tls
  rules:
    - host: ws.staging.abianzo.example.com
