apiVersion: apps/v1
kind: Deployment
metadata:
  name: abzora-api
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abzora-worker
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abzora-websocket
spec:
  replicas: 1
