apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abzora-admin-ingress
spec:
  tls:
    - hosts:
        - admin.staging.abzora.example.com
      secretName: staging-abzora-admin-tls
  rules:
    - host: admin.staging.abzora.example.com
