apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: abianzo-api-hpa
  namespace: abianzo
spec:
  minReplicas: 2
  maxReplicas: 8
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: abianzo-worker-hpa
  namespace: abianzo
spec:
  minReplicas: 1
  maxReplicas: 6
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: abianzo-websocket-hpa
  namespace: abianzo
spec:
  minReplicas: 1
  maxReplicas: 5
