apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patch-prod.yaml
  - path: patch-ingress-api.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: abianzo-api-ingress
  - path: patch-ingress-websocket.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: abianzo-websocket-ingress
  - path: patch-ingress-admin.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: abianzo-admin-ingress
  - path: patch-ingress-webhook.yaml
    target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: abianzo-webhook-ingress
