apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abianzo-websocket-ingress
  annotations:
    nginx.ingress.kubernetes.io/limit-connections: "500"
spec:
  tls:
    - hosts:
        - ws.abianzo.com
      secretName: prod-abianzo-ws-tls
  rules:
    - host: ws.abianzo.com
