apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abianzo-webhook-ingress
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "180"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
spec:
  tls:
    - hosts:
        - hooks.abianzo.com
      secretName: prod-abianzo-hooks-tls
  rules:
    - host: hooks.abianzo.com
