apiVersion: apps/v1
kind: Deployment
metadata:
  name: abianzo-api
  namespace: abianzo
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abianzo-worker
  namespace: abianzo
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: abianzo-websocket
  namespace: abianzo
spec:
  replicas: 3
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: abianzo-api-hpa
  namespace: abianzo
spec:
  minReplicas: 4
  maxReplicas: 30
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: abianzo-worker-hpa
  namespace: abianzo
spec:
  minReplicas: 3
  maxReplicas: 40
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: abianzo-websocket-hpa
  namespace: abianzo
spec:
  minReplicas: 3
  maxReplicas: 20
